"""Entry point for the CLIENT machine (the controller)."""
import sys
import logging
logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')

from PyQt6.QtWidgets import (
    QApplication, QDialog, QVBoxLayout, QFormLayout,
    QLabel, QLineEdit, QPushButton, QComboBox,
    QStackedWidget, QWidget, QMessageBox, QCheckBox,
)
from PyQt6.QtCore import Qt


class ConnectDialog(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowTitle('EcranDistant — Connect')
        self.setFixedWidth(370)
        self.setWindowFlag(Qt.WindowType.WindowContextHelpButtonHint, False)

        root = QVBoxLayout(self)
        root.setSpacing(10)

        # Mode selector
        root.addWidget(QLabel('Connection mode:'))
        self._mode = QComboBox()
        self._mode.addItems(['Direct (LAN)', 'Via relay server (internet)'])
        self._mode.currentIndexChanged.connect(self._on_mode)
        root.addWidget(self._mode)

        # Stacked pages
        self._stack = QStackedWidget()
        root.addWidget(self._stack)

        # Page 0: Direct
        p0 = QWidget()
        f0 = QFormLayout(p0)
        self._host_edit = QLineEdit('127.0.0.1')
        self._port_edit = QLineEdit('8765')
        f0.addRow('Host IP:', self._host_edit)
        f0.addRow('Port:',    self._port_edit)
        self._stack.addWidget(p0)

        # Page 1: Relay
        p1 = QWidget()
        f1 = QFormLayout(p1)
        self._relay_edit = QLineEdit('ecrandistant-relay.onrender.com')
        self._relay_edit.setPlaceholderText('ecrandistant-relay.onrender.com')
        self._sid_edit = QLineEdit()
        self._sid_edit.setPlaceholderText('6-character code from host')
        f1.addRow('Relay URL:',  self._relay_edit)
        f1.addRow('Session ID:', self._sid_edit)
        self._stack.addWidget(p1)

        # Password
        pw = QFormLayout()
        self._pass_edit = QLineEdit()
        self._pass_edit.setEchoMode(QLineEdit.EchoMode.Password)
        self._pass_edit.setPlaceholderText('6-digit code from host')
        pw.addRow('Password:', self._pass_edit)
        root.addLayout(pw)

        # TLS checkbox
        self._tls_cb = QCheckBox('Use TLS encryption (wss://)')
        self._tls_cb.setToolTip(
            'Enable if the host was started with --tls.\n'
            'Requires cert.pem / key.pem generated by generate_cert.py'
        )
        root.addWidget(self._tls_cb)

        # Connect button
        btn = QPushButton('Connect')
        btn.setDefault(True)
        btn.clicked.connect(self._validate)
        root.addWidget(btn)

        self._pass_edit.returnPressed.connect(self._validate)
        self.adjustSize()

    def _on_mode(self, index: int):
        self._stack.setCurrentIndex(index)
        self._tls_cb.setVisible(index == 0)  # TLS only for direct
        self.adjustSize()

    def _validate(self):
        if self._mode.currentIndex() == 0:
            if not self._host_edit.text().strip():
                QMessageBox.warning(self, 'Missing', 'Enter the host IP.')
                return
        else:
            if not self._relay_edit.text().strip():
                QMessageBox.warning(self, 'Missing', 'Enter the relay URL.')
                return
            if not self._sid_edit.text().strip():
                QMessageBox.warning(self, 'Missing', 'Enter the session ID.')
                return
        if not self._pass_edit.text():
            QMessageBox.warning(self, 'Missing', 'Enter the password.')
            return
        self.accept()

    def params(self) -> dict:
        mode = self._mode.currentIndex()
        relay_url = self._relay_edit.text().strip()
        # Convert http/https to ws/wss automatically
        if relay_url.startswith('https://'):
            relay_url = 'wss://' + relay_url[8:]
        elif relay_url.startswith('http://'):
            relay_url = 'ws://' + relay_url[7:]
        elif relay_url and not relay_url.startswith('ws://') and not relay_url.startswith('wss://'):
            relay_url = 'wss://' + relay_url
        return {
            'mode':       'direct' if mode == 0 else 'relay',
            'host':       self._host_edit.text().strip(),
            'port':       int(self._port_edit.text().strip() or '8765'),
            'relay_url':  relay_url,
            'session_id': self._sid_edit.text().strip().upper(),
            'password':   self._pass_edit.text(),
            'use_tls':    self._tls_cb.isChecked(),
        }


def main():
    app = QApplication(sys.argv)
    app.setApplicationName('EcranDistant')

    dialog = ConnectDialog()
    if dialog.exec() != QDialog.DialogCode.Accepted:
        sys.exit(0)

    p = dialog.params()

    from client.connection import ConnectionWorker
    from client.viewer import ViewerWindow

    if p['mode'] == 'direct':
        worker = ConnectionWorker(
            password=p['password'],
            host=p['host'],
            port=p['port'],
            use_tls=p['use_tls'],
        )
    else:
        worker = ConnectionWorker(
            password=p['password'],
            relay_url=p['relay_url'],
            session_id=p['session_id'],
        )

    window = ViewerWindow(worker)

    worker.frame_received.connect(window.on_frame)
    worker.connected.connect(window.on_connected)
    worker.monitor_changed.connect(window.on_monitor_changed)
    worker.clipboard_received.connect(window.on_clipboard_received)
    worker.audio_chunk.connect(
        lambda pcm, sr, ch: worker.play_audio(pcm, sr, ch)
    )
    worker.auth_failed.connect(
        lambda msg: QMessageBox.critical(window, 'Auth failed', msg)
    )
    worker.disconnected.connect(
        lambda msg: QMessageBox.warning(window, 'Disconnected', msg)
    )

    window.show()
    worker.start()

    sys.exit(app.exec())


if __name__ == '__main__':
    main()
